### ISSUE TITLE
Feature Request: Azerite Trait Icon Anchor Location Options

### ISSUE THREAD

**Issue by Merxxz** [Jokair9/AzeriteTooltip#12]
I've been manually modifying your lua code to place the azerite trait icons at the top of the item icon. This allows me to see both the traits selected and the ilvl of the item as displayed by another addon. Can you add some options to change the location between bottom and top?

![](https://i.imgur.com/RQs33bk.png)

**Comment by solaldunckel** [comment]
Hey,

I've implemented this feature in the new release. Thanks!
