### ISSUE TITLE
hooksecurefunc (Error)

### ISSUE THREAD

**Issue by HDMOVIESOURCE** [Jokair9/AzeriteTooltip#14]
Been getting this on login all the time.

58x AzeriteTooltip\AzeriteTooltip-2.0.6.lua:152: Usage: hooksecurefunc([table,] "function", hookfunc)
[C]: in function `hooksecurefunc'
AzeriteTooltip\AzeriteTooltip-2.0.6.lua:152: in function <AzeriteTooltip\AzeriteTooltip.lua:146>
[C]: ?
...ns\AzeriteTooltip\libs\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <...ns\AzeriteTooltip\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
...ns\AzeriteTooltip\libs\AceAddon-3.0\AceAddon-3.0-12.lua:527: in function `EnableAddon'
...ns\AzeriteTooltip\libs\AceAddon-3.0\AceAddon-3.0-12.lua:620: in function <...ns\AzeriteTooltip\libs\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:448: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:567: in function `TimeManager_LoadUI'
FrameXML\UIParent.lua:1240: in function <FrameXML\UIParent.lua:1138>
[C]: ?

**Comment by Nukme** [comment]
change line 152 of AzeriteTooltip.lua to
```
hooksecurefunc(Bagnon.Item, "Update", function(self)
```

**Comment by HDMOVIESOURCE** [comment]
hooksecurefunc(Bagnon.Item, "Update", function(self)

Fixed the issue, thank you.

**Comment by solaldunckel** [comment]
Should be fixed in the new version.
