### ISSUE TITLE
LUA bug

### ISSUE THREAD

**Issue by Vikirnoff** [Jokair9/AzeriteTooltip#16]
I'm getting this bug. Not sure why or what is causing it. Thanks! 

1x AzeriteTooltip\AzeriteTooltip-2.0.6.lua:152: Usage: hooksecurefunc([table,] "function", hookfunc)
[C]: in function `hooksecurefunc'
AzeriteTooltip\AzeriteTooltip-2.0.6.lua:152: in function <AzeriteTooltip\AzeriteTooltip.lua:146>
[C]: ?
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:527: in function `EnableAddon'
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:620: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:448: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:491: in function `CombatLog_LoadUI'
FrameXML\UIParent.lua:1242: in function <FrameXML\UIParent.lua:1138>

**Comment by solaldunckel** [comment]
Should be fixed in the new version.
