### ISSUE TITLE
8.1.5 error

### ISSUE THREAD

**Issue by soulyouth** [Jokair9/AzeriteTooltip#5]
1x AzeriteTooltip\AzeriteTooltip-2.0.2.lua:162: Usage: SecureHookScript(object, method, [handler]): You can only hook a script on a frame object
[C]: ?
...Ons\ElvUI\Libraries\Ace3\AceHook-3.0\AceHook-3.0-8.lua:143: in function <...Ons\ElvUI\Libraries\Ace3\AceHook-3.0\AceHook-3.0.lua:118>
...Ons\ElvUI\Libraries\Ace3\AceHook-3.0\AceHook-3.0-8.lua:411: in function `SecureHookScript'
AzeriteTooltip\AzeriteTooltip-2.0.2.lua:162: in function <AzeriteTooltip\AzeriteTooltip.lua:146>
[C]: ?
...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:70: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:527: in function `EnableAddon'
...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:620: in function <...s\ElvUI\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:605>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:446: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:565: in function `TimeManager_LoadUI'
FrameXML\UIParent.lua:1192: in function <FrameXML\UIParent.lua:1090>

**Comment by HDMOVIESOURCE** [comment]
Im getting the exact same error.
