### ISSUE TITLE
Show Traits in Bag/Character Frame not working (8.1.5).

### ISSUE THREAD

**Issue by Brit89** [Jokair9/AzeriteTooltip#7]
The 2 main Trait icons are not showing, when both Bag and Character Frames are enabled, on the gear. I've tried it with all add-ons off (inc. Elvui) except AzeriteTooltip, tried /reloading, rolling back to an earlier patch/reinstalling - nothing. I updated this on EU's patch day fyi, so not when this was out in NA.

![WoWScrnShot_031319_075724](https://user-images.githubusercontent.com/48509776/54262386-f40cbe00-4565-11e9-996b-759c9bc3836a.jpg)

**Comment by solaldunckel** [comment]
It should be fixed on Character Frame in latest update. Bags Icons are only supported with default bags + Bagnon.

**Comment by Brit89** [comment]
Thanks, the 2.0.5 patch did the trick!
